# Generated by Django 2.0.2 on 2018-05-14 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='born',
            field=models.DateField(default=datetime.datetime(2018, 5, 14, 4, 14, 47, 549938)),
        ),
    ]
