# Generated by Django 2.0.2 on 2018-05-14 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180514_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='born',
            field=models.DateField(default=datetime.datetime(2018, 5, 14, 4, 55, 2, 379365)),
        ),
    ]
