# Generated by Django 2.0.2 on 2018-05-14 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180514_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='born',
            field=models.DateField(default=datetime.datetime(2018, 5, 14, 20, 21, 55, 698582)),
        ),
    ]
