# Generated by Django 2.0.2 on 2018-02-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page_block_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='core.ServiceSubcategory'),
        ),
    ]
