# Generated by Django 2.0.2 on 2018-02-26 16:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180226_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='block_html_2',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
