# Generated by Django 2.0.2 on 2018-02-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_page_block_html_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1500)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
