# Generated by Django 2.0.2 on 2018-02-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_page_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='gender',
            new_name='template',
        ),
    ]
