# Generated by Django 2.0.2 on 2018-02-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180227_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='pageskeleton_ptr',
        ),
        migrations.RemoveField(
            model_name='servicesubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicesubcategory',
            name='pageskeleton_ptr',
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='core.Page'),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceSubcategory',
        ),
    ]
