# Generated by Django 2.0.2 on 2018-02-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180227_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('home', 'home'), ('building', 'building')], default='home', max_length=30),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
