# Generated by Django 2.0.2 on 2018-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180228_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background',
            field=models.ImageField(blank=True, upload_to='page/background'),
        ),
    ]
