# Generated by Django 2.0.2 on 2018-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_page_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('home', 'home.html'), ('services', 'service.html'), ('decor_list', 'decor-list.html'), ('page', 'page.html'), ('portfolio', 'portfolio.html'), ('contact', 'contact.html')], default='home', max_length=30),
        ),
    ]
