# Generated by Django 2.0.2 on 2018-03-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180306_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageskeleton',
            name='in_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('home', 'home.html'), ('services', 'service.html'), ('decor_list', 'decor-list.html'), ('decor_detail', 'decor-detail.html'), ('page', 'page.html'), ('portfolio', 'portfolio.html'), ('contact', 'contact.html')], default='home', max_length=30),
        ),
    ]
