# Generated by Django 2.0.2 on 2018-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pageskeleton_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageskeleton',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pageskeleton',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='pageskeleton',
            name='meta_title',
            field=models.CharField(default='Поменять title страницы', max_length=80),
        ),
    ]
