# Generated by Django 2.0.2 on 2018-03-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180324_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageskeleton',
            name='keywords',
        ),
    ]
