# Generated by Django 2.0.2 on 2018-05-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_pageskeleton_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageskeleton',
            name='adress',
        ),
    ]
