# Generated by Django 2.0.2 on 2018-05-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_pageskeleton_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='padej',
            field=models.CharField(default='Пятегорске', max_length=300),
        ),
    ]
